/**
 * Clés `data-test` présentes dans `src/`. Source unique de vérité pour `cy.getBySel`.
 *
 * Le tableau est `as const` pour que `DataTestKey` soit une union littérale :
 * une faute de frappe dans une spec devient une erreur de compilation, pas un
 * échec au runtime après 40 secondes de test (ARCHITECTURE.md §4, couche L2).
 *
 * Ajouter un `data-test` dans `src/` impose d'ajouter sa clé ici
 * (.claude/rules/testing.md #9).
 */
export const DATA_TEST_KEYS = [
  "amount-range-filter-drawer",
  "amount-range-filter-drawer-close",
  "app-name-logo",
  "bankaccount-delete",
  "bankaccount-form",
  "bankaccount-list",
  "bankaccount-new",
  "bankaccount-submit",
  "comments-list",
  "date-range-filter-drawer",
  "date-range-filter-drawer-close",
  "drawer-icon",
  "empty-list-children",
  "empty-list-header",
  "error-state",
  "error-state-message",
  "error-state-retry",
  "list-skeleton",
  "main",
  "nav-contacts-tab",
  "nav-personal-tab",
  "nav-public-tab",
  "nav-top-new-transaction",
  "nav-top-notifications-count",
  "nav-top-notifications-link",
  "nav-transaction-tabs",
  "new-transaction-create-another-transaction",
  "new-transaction-return-to-transactions",
  "notifications-list",
  "sidenav",
  "sidenav-bankaccounts",
  "sidenav-home",
  "sidenav-notifications",
  "sidenav-signout",
  "sidenav-toggle",
  "sidenav-user-balance",
  "sidenav-user-full-name",
  "sidenav-user-settings",
  "sidenav-username",
  "signin-error",
  "signin-password",
  "signin-remember-me",
  "signin-submit",
  "signin-username",
  "signup",
  "signup-confirmPassword",
  "signup-first-name",
  "signup-last-name",
  "signup-password",
  "signup-submit",
  "signup-title",
  "signup-username",
  "transaction-comment-count",
  "transaction-create-form",
  "transaction-create-submit-payment",
  "transaction-create-submit-request",
  "transaction-description",
  "transaction-detail-header",
  "transaction-detail-loading",
  "transaction-like-count",
  "transaction-list",
  "transaction-list-empty-create-transaction-button",
  "transaction-list-filter-amount-clear-button",
  "transaction-list-filter-amount-range",
  "transaction-list-filter-amount-range-button",
  "transaction-list-filter-amount-range-slider",
  "transaction-list-filter-amount-range-text",
  "transaction-list-filter-date-clear-button",
  "transaction-list-filter-date-range-button",
  "transaction-receiver-avatar",
  "transaction-sender-avatar",
  "user-list-search-input",
  "user-onboarding-dialog",
  "user-onboarding-dialog-content",
  "user-onboarding-dialog-title",
  "user-onboarding-logout",
  "user-onboarding-next",
  "user-settings-email-input",
  "user-settings-firstName-input",
  "user-settings-form",
  "user-settings-lastName-input",
  "user-settings-phoneNumber-input",
  "user-settings-submit",
  "users-list",
] as const;

export type DataTestKey = (typeof DATA_TEST_KEYS)[number];
